apiVersion: apps/v1
kind: Deployment
metadata:
  name: vegeta-controller
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    spec:
      containers:
        - name: controller
          image: vegeta-controller
          imagePullPolicy: Never
