apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vegeta-controller
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - batch
    resources:
      - jobs/status
    verbs:
      - get
  - apiGroups:
      - vegeta.kaidotdev.github.io
    resources:
      - attacks
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - vegeta.kaidotdev.github.io
    resources:
      - attacks/status
    verbs:
      - get
      - patch
      - update
