namespace: kube-system

resources:
  - crd/vegeta.kaidotdev.github.io_attacks.yaml
  # +kubebuilder:scaffold:crdkustomizeresource
  - cluster_role.yaml
  - cluster_role_binding.yaml
  - deployment.yaml
  - role.yaml
  - role_binding.yaml
  - service_account.yaml
